#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export HISTFILE="$HOME/.zsh_history"
export HISTSIZE=10000000
export SAVEHIST=10000000
export LSCOLORS=excxFxFxBxxfxfxBxBxexe
export LC_ALL=en_US.UTF-8


# SLOW!
# if command -v pyenv 1>/dev/null 2>&1; then
#   eval "$(pyenv init - zsh --no-rehash)"
# fi

export TZ='America/New_York'
export PYENV_ROOT="$HOME/.pyenv"
export PATH="/usr/local/bin:${HOME}/bin:$/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:$HOME/.rvm/bin:$PYENV_ROOT/bin:$PATH"
export EDITOR=vim
export GIT_EDITOR=vim
